# Generated by Django 3.1.5 on 2021-01-19 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210119_2300'),
        ('realworld', '0003_userarticlefavorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'verbose_name_plural': 'Article Tag'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tag'},
        ),
        migrations.AlterModelOptions(
            name='userarticlefavorites',
            options={'verbose_name_plural': 'User Favorite Articles'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realworld.article'),
        ),
        migrations.AlterField(
            model_name='userarticlefavorites',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realworld.article'),
        ),
        migrations.AlterField(
            model_name='userarticlefavorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
        ),
    ]
