# Generated by Django 3.1.5 on 2021-01-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name_plural': 'Follow'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User'},
        ),
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
