# Generated by Django 3.1.5 on 2021-01-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210119_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
