# Generated by Django 3.1.5 on 2021-01-31 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_phone',
            new_name='phone',
        ),
    ]
