# Generated by Django 3.1.5 on 2021-01-31 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210131_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='user_phone',
        ),
    ]
